### ISSUE TITLE
Make `CACHE_URL` a shared value

### ISSUE THREAD

**Issue by jnm** [kobotoolbox/kobo-helm-chart#13]
It's needed by both kpi and kobocat but currently set for kpi only.

https://github.com/kobotoolbox/kobo-helm-chart/blob/2fffe8fa657e5071a5f8c5e5730df20c82f011b0/values.yaml#L55

**Comment by bufke** [comment]
We discussed a general redis url without DB number. This would set every redis need. If a redis env var is set in kpi/kc explicitly, it would take priority.
