### ISSUE TITLE
Support for external DB connections

### ISSUE THREAD

**Issue by Yann-J** [kobotoolbox/kobo-helm-chart#41]
Hey there, first off, I cannot tell you how happy we are that Kobotoolbox team is considering maintaining an official Helm chart, this is definitely the way to go for large installations!

Me and my team have been [maintaining our own](https://github.com/one-acre-fund/oaf-public-charts/tree/main/charts/kobotoolbox) for a while now, with some success, but obviously with very limited knowledge of the application architecture (and for that matter, of Django, Celery and the other tech!), so it's a very naive setup.

I'm happy that some of my suggestions from [this old ticket](https://github.com/kobotoolbox/kpi/issues/4152) (such as separate pods for the celery workers) are already implemented!

One gap I see with our existing chart is the (apparent?) lack of support for an external DB connection, i.e. not installed through the chart (in our case we use Azure managed DB instances in PRD).

We might contribute a PR about this soon...

**Comment by bufke** [comment]
Hello, indeed and you're attributed in the readme here as well! It was helpful to see some examples when creating this.

We currently can set database url as a k8s secret to environment variable mapping. [Example](https://github.com/kobotoolbox/kobo-helm-chart/blob/main/values.yaml#L79). We recently now support extra volume mounts. We may soon add support for AWS Secrets Manager, or really just add what is needed for this to be set up externally. It's currently possible to mount a secret as a file. I'm not sure how Azure works here but I know they have a similar product. Please post any ideas you have and PR.

Note this project is somewhat based on [django-helm-chart](https://gitlab.com/burke-software/django-helm-chart) which is another project I made. I would like to keep it at least somewhat aligned.

**Comment by bufke** [comment]
Closing this but feel free to propose changes in a pull request.
