### ISSUE TITLE
KPI and Kobo secrets missing in pre-install jobs

### ISSUE THREAD

**Issue by bisonlou** [kobotoolbox/kobo-helm-chart#42]
The pre-install jobs are failing cause they cannot find some environment variables that are to be provided as secrets.
For example, the azure account key exists in the secrets for both KPI and KOBO but is not ported to the pre-install hooks.

`django.core.exceptions.ImproperlyConfigured: Set the AZURE_ACCOUNT_KEY environment variable`

**Comment by bufke** [comment]
Please use our forum for help requests. See our new [issue template](https://github.com/kobotoolbox/kobo-helm-chart/blob/main/.github/ISSUE_TEMPLATE/bug-report.md?plain=1). 

If you have an idea for a feature request around Azure, please reopen and submit a pull request.
