### ISSUE TITLE
Need help to use the chart

### ISSUE THREAD

**Issue by fredericmazzini** [kobotoolbox/kobo-helm-chart#56]
Hi,

I'm trying to use the chart, but I encounter many problems:

- when I want to preview a form I get this error :
![image](https://github.com/kobotoolbox/kobo-helm-chart/assets/19612433/9da4723c-892b-46ce-8e41-9758c8f444c3)
In the kpi logs file there is this line (404 error code)
```
[pid: 303|app: 0|req: 9196/18377] 100.64.5.234, 100.64.1.3 () {46 vars in 1050 bytes} [Thu Oct 12 15:58:31 2023] GET /api/v2/asset_snapshots/sRDgg7EHUB2M5WyiAzCSMc/formList?formID=sRDgg7EHUB2M5WyiAzCSMc => generated
 129 bytes in 30 msecs (HTTP/1.0 404) 8 headers in 260 bytes (1 switches on core 0)
```
- when I want to view a photo uploaded from Kobocollect 
![image](https://github.com/kobotoolbox/kobo-helm-chart/assets/19612433/632caabc-474e-412f-8a5b-6a170dbaee3c)
the following line appear in kpi logs file (404 error code) :
```
[pid: 302|app: 0|req: 9205/18425] 172.16.4.4, 100.64.1.3 () {64 vars in 1586 bytes} [Thu Oct 12 16:01:33 2023] GET /protected/mazzini/attachments/6a605b7c93b84ed5a77b6d2ab4e1221e/b3c153a3-0512-42cd-a589-9c49ba04dac5
/169553-16_19_31.png => generated 179 bytes in 28 msecs (HTTP/1.0 404) 8 headers in 240 bytes (1 switches on core 0)

```
Could you help me solve these issues ?

Regards,

Fred

**Comment by bufke** [comment]
Please use our forum for help requests. See our new [issue template](https://github.com/kobotoolbox/kobo-helm-chart/blob/main/.github/ISSUE_TEMPLATE/bug-report.md?plain=1).
